# example workflow for Polaris SaaS scans using the Bridge CLI
name: polaris-bridge

on:
  push:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Scan
      env:
        BRIDGE_POLARIS_SERVERURL: ${{ secrets.POLARIS_SERVERURL }}
        BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESSTOKEN }}
        BRIDGE_POLARIS_APPLICATION_NAME: chuckaude-${{ github.event.repository.name }}
        BRIDGE_POLARIS_PROJECT_NAME: chuckaude-${{ github.event.repository.name }}
        BRIDGECLI_LINUX64: ${{ secrets.BRIDGECLI_LINUX64 }}
      run: |
        curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        $RUNNER_TEMP/bridge --verbose --stage polaris polaris.assessment.types=SAST,SCA
